version: '3.4'

services: 
  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  fastify:
    image: fastify-nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
