version: '3.8'

services: 
  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  fastify:
    image: fastify/node-js
    build:
      context: .
      dockerfile: ./fastify/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080

volumes:
  database-data: